# Generated by Django 4.2 on 2025-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHEF', 'Chef'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
